//
// Created by Samet Arslan on 27.08.2025.
//

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
    volatile uint32_t *pRCCAhb1Enr = (uint32_t)0x40023830;
    *pRCCAhb1Enr |= (1u << 3);

    volatile uint32_t *pGPIODModer = (uint32_t)0x40020C00;
    *pGPIODModer |= (1u << 24);
    *pGPIODModer |= (1u << 26);
    *pGPIODModer |= (1u << 28);
    *pGPIODModer |= (1u << 30);

    volatile uint32_t *pGPIODODR = (uint32_t)0x40020C14;
    *pGPIODODR |= (1u << 12);
    *pGPIODODR |= (1u << 13);
    *pGPIODODR |= (1u << 14);
    *pGPIODODR |= (1u << 15);

    for(;;);
}


